**House Price Prediction**

*The purpose of this project is to predict the house price based on features using ML*

**1. Import Libraries and data**

In [351]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("c:/Users/haris/house-price-prediction/data/raw/house_data.csv")

**2. Initial Data Understanding and EDA**

In [134]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,5/2/2014 0:00,313000.0,3,1.50,1340,7912.0,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,5/2/2014 0:00,2384000.0,5,2.50,3650,9050.0,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,5/2/2014 0:00,342000.0,3,2.00,1930,11947.0,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,5/2/2014 0:00,420000.0,3,2.25,2000,8030.0,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,5/2/2014 0:00,550000.0,4,2.50,1940,10500.0,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [70]:
df.shape

(4600, 18)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4598 non-null   float64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [28]:
df.describe().round(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4600.00,4600.00,4600.00,4600.00,4598.00,4600.00,4600.00,4600.00,4600.00,4600.00,4600.00,4600.00,4600.00
mean,551962.99,3.40,2.16,2139.35,14855.77,1.51,0.01,0.24,3.45,1827.27,312.08,1970.79,808.61
std,563834.70,0.91,0.78,963.21,35891.90,0.54,0.08,0.78,0.68,862.17,464.14,29.73,979.41
min,0.00,0.00,0.00,370.00,638.00,1.00,0.00,0.00,1.00,370.00,0.00,1900.00,0.00
25%,322875.00,3.00,1.75,1460.00,5000.25,1.00,0.00,0.00,3.00,1190.00,0.00,1951.00,0.00
50%,460943.46,3.00,2.25,1980.00,7683.00,1.50,0.00,0.00,3.00,1590.00,0.00,1976.00,0.00
75%,654962.50,4.00,2.50,2620.00,11003.75,2.00,0.00,0.00,4.00,2300.00,610.00,1997.00,1999.00
max,26590000.00,9.00,8.00,13540.00,1074218.00,3.50,1.00,4.00,5.00,9410.00,4820.00,2014.00,2014.00

In [84]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         2
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [85]:
#Analysis on numerical columns to determine impact on price
df.corr(numeric_only=True)["price"].sort_values()

yr_renovated    -0.028774
yr_built         0.021857
condition        0.034915
sqft_lot         0.050401
waterfront       0.135648
floors           0.151461
bedrooms         0.200336
sqft_basement    0.210427
view             0.228504
bathrooms        0.327110
sqft_above       0.367570
sqft_living      0.430410
price            1.000000
Name: price, dtype: float64

In [76]:
df.groupby("yr_renovated")["price"].mean().sort_index().round(2)

yr_renovated
0        565275.24
1912     496441.66
1913     440000.00
1923     653727.82
1934     533691.67
1945     930142.86
1948     410000.00
1953     270000.00
1954     443033.33
1955     474500.00
1956     685820.00
1958     415500.00
1960     160000.00
1963     281835.83
1966     750500.00
1968     457311.11
1969     402086.36
1970     689628.21
1971     470911.00
1972     388685.34
1974     467083.33
1975          0.00
1977     346750.00
1978     500000.00
1979     589081.71
1980     571250.00
1981     630000.00
1982     396896.71
1983     451284.15
1984     497000.00
1985     560325.86
1986     750100.00
1987     590000.00
1988     563850.92
1989     504816.28
1990     786344.53
1991    1675000.00
1992     546204.47
1993     574784.29
1994     492349.12
1995    1127975.00
1996     535247.73
1997     375814.29
1998     494572.65
1999     426884.78
2000     563677.98
2001     616414.39
2002     552518.07
2003     598587.41
2004     468422.76
2005     485843.16
2006     537524.58
2007     921428.57
2008     446594.88
2009     568730.15
2010     504082.78
2011     430266.67
2012     383622.18
2013     501093.25
2014     555261.42
Name: price, dtype: float64

In [296]:
#Analyse the condition column
df.groupby("condition")["price"].mean().round(2)

condition
1    306633.33
2    324373.75
3    550111.52
4    533647.29
5    637041.32
Name: price, dtype: float64

In [55]:
#analyze categorical columns
df["city"].nunique()

44

In [56]:
df["city"].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Issaquah                187
Kirkland                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
SeaTac                   29
Tukwila                  29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Medina                   11
Fall City                11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Preston                   2
Milton                    2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [63]:
df.groupby("city")["price"].mean().sort_values(ascending=False).round(2)

city
Medina                 2046559.09
Clyde Hill             1321945.45
Yarrow Point           1194837.50
Mercer Island          1123817.62
Bellevue                847180.66
Beaux Arts Village      745000.00
Fall City               692681.82
Sammamish               686917.58
Redmond                 667649.53
Newcastle               666046.70
Kirkland                651583.59
Woodinville             609565.02
Issaquah                596163.75
Seattle                 579837.47
Preston                 562450.00
Snoqualmie              536305.30
Snoqualmie Pass         525000.00
Ravensdale              514071.43
Carnation               508751.95
Normandy Park           506793.06
Bothell                 481441.89
Vashon                  472556.90
Lake Forest Park        448475.00
Kenmore                 447494.04
Kent                    439492.44
Inglewood-Finn Hill     425000.00
Shoreline               420392.36
Duvall                  403994.13
North Bend              399565.71
Renton                  377040.97
Burien                  348947.25
Black Diamond           339605.56
Maple Valley            336474.91
Tukwila                 308290.07
Enumclaw                307614.58
Des Moines              304992.55
Auburn                  299340.44
Covington               296230.40
Federal Way             289887.70
Milton                  285000.00
SeaTac                  245290.62
Skykomish               233000.00
Pacific                 225233.33
Algona                  207288.00
Name: price, dtype: float64

In [65]:
city_analysis = df.groupby("city")["price"].agg(
    ["mean", "count"]
).sort_values(
    by="mean",
    ascending=False
).round()

city_analysis

                          mean  count
city
Medina               2046559.0     11
Clyde Hill           1321945.0     11
Yarrow Point         1194838.0      4
Mercer Island        1123818.0     86
Bellevue              847181.0    286
Beaux Arts Village    745000.0      1
Fall City             692682.0     11
Sammamish             686918.0    175
Redmond               667650.0    235
Newcastle             666047.0     33
Kirkland              651584.0    187
Woodinville           609565.0    115
Issaquah              596164.0    187
Seattle               579837.0   1573
Preston               562450.0      2
Snoqualmie            536305.0     71
Snoqualmie Pass       525000.0      1
Ravensdale            514071.0      7
Carnation             508752.0     22
Normandy Park         506793.0     18
Bothell               481442.0     33
Vashon                472557.0     29
Lake Forest Park      448475.0     36
Kenmore               447494.0     66
Kent                  439492.0    185
Inglewood-Finn Hill   425000.0      1
Shoreline             420392.0    123
Duvall                403994.0     42
North Bend            399566.0     50
Renton                377041.0    293
Burien                348947.0     74
Black Diamond         339606.0      9
Maple Valley          336475.0     96
Tukwila               308290.0     29
Enumclaw              307615.0     28
Des Moines            304993.0     58
Auburn                299340.0    176
Covington             296230.0     43
Federal Way           289888.0    148
Milton                285000.0      2
SeaTac                245291.0     29
Skykomish             233000.0      3
Pacific               225233.0      6
Algona                207288.0      5

In [90]:
from ydata_profiling import ProfileReport

In [95]:
prof=ProfileReport(df)
prof.to_file(output_file='hpp_output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/18 [00:00<?, ?it/s]
100%|██████████| 18/18 [00:00<00:00, 86.99it/s][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

**3. Seperate X and y and feature selection**

In [250]:
#Split input and output data
y=df["price"]
X=df.drop(["date","price","country","street"],axis=1)

**4. Train Test Split**

In [251]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

**5. Preprocessing**

In [359]:
#column transaformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
numerical_cols = ['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']
categorical_cols=['statezip','city']
# transformer=ColumnTransformer(transformers=[
#     ('tnf1',SimpleImputer(),['sqft_lot']),
#     ('tnf2',StandardScaler(),numerical_cols),
#     ('tnf3',OneHotEncoder(),categorical_cols)
# ])

from sklearn.pipeline import Pipeline
numerical_transformer=Pipeline([
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler()) 
])
transformer=ColumnTransformer([
('num',numerical_transformer,numerical_cols),
('cat',OneHotEncoder(handle_unknown='ignore'),categorical_cols)
])
transformer.fit(X_train)
X_train_transformed=transformer.transform(X_train)
X_test_transformed=transformer.transform(X_test)

**Practice code**

In [361]:
# from sklearn.linear_model import LinearRegression
# model=LinearRegression()
# model.fit(X_train_transformed,y_train)
# y_pred=model.predict(X_test_transformed)
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# mae=mean_absolute_error(y_test,y_pred)
# mse=mean_squared_error(y_test,y_pred)
# r2=r2_score(y_test,y_pred)
# print(mae)
# print(mse)
# print(r2)
# from sklearn.ensemble import RandomForestRegressor
# rf_model=RandomForestRegressor(n_estimators=300, random_state=42)
# rf_model.fit(X_train_transformed,y_train)
# y_pred_rf=rf_model.predict(X_test_transformed)
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# mae_rf=mean_absolute_error(y_test,y_pred_rf)
# mse_rf=mean_squared_error(y_test,y_pred_rf)
# r2_rf=r2_score(y_test,y_pred_rf)
# print(mae_rf)
# print(mse_rf)
# print(r2_rf)
# from sklearn.ensemble import GradientBoostingRegressor
# gb_model=GradientBoostingRegressor(n_estimators=500,learning_rate=0.1,max_depth=3, random_state=0)
# gb_model.fit(X_train_transformed,y_train)
# y_pred_gb=gb_model.predict(X_test_transformed)
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# mae_gb=mean_absolute_error(y_test,y_pred_gb)
# mse_gb=mean_squared_error(y_test,y_pred_gb)
# r2_gb=r2_score(y_test,y_pred_gb)
# print(mae_gb)
# print(mse_gb)
# print(r2_gb)

**6. Model Comparison**

In [347]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
models={'Linear Regression':LinearRegression(),
        'Random Forest':RandomForestRegressor(n_estimators=100,random_state=42),
        'Gradient Boost':GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)
}

In [383]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
results=[]
for name, model in models.items():
    model.fit(X_train_transformed,y_train)
    y_pred=model.predict(X_test_transformed)
    mae=mean_absolute_error(y_test,y_pred)
    mse=mean_squared_error(y_test,y_pred)
    r2=r2_score(y_test,y_pred)
    result=results.append([name,mae,mse,r2])

In [387]:
results_df=pd.DataFrame(results, columns=["Model","MAE","MSE","R2"])
results_df.sort_values("R2", ascending=False)

               Model            MAE           MSE        R2
0  Linear Regression  112790.865001  4.036315e+10  0.727181
2     Gradient Boost  124738.008021  4.665775e+10  0.684635
1      Random Forest  141131.465755  2.066447e+11 -0.396734

**7. Final Model**

In [389]:
from sklearn.linear_model import LinearRegression
final_model=LinearRegression()
final_model.fit(X_train_transformed,y_train)
y_pred=final_model.predict(X_test_transformed)

**8. Create Final Pipeline**

In [392]:
from sklearn.pipeline import Pipeline
final_pipeline=Pipeline([
    ('preprocessor',transformer),
    ('model',LinearRegression())
])

transformer.fit(X_train)
X_train_transformed = transformer.transform(X_train)
final_model.fit(X_train_transformed, y_train)
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['bedrooms', 'bathrooms',
                                                   'sqft_living', 'sqft_lot',
                                                   'floors', 'waterfront',
                                                   'view', 'condition',
                                                   'sqft_above',
                                                   'sqft_basement', 'yr_built',
                                                   'yr_renovated']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['statezip', 'city'])])),
                ('model', LinearRegression())])

In [393]:
y_pred = final_pipeline.predict(X_test)

In [394]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 112790.86500089367
RMSE: 200905.81448675308
R2: 0.7271809629012022

**9. Save Pipeline**

In [396]:
import joblib
joblib.dump(final_pipeline,"C:/Users/haris/house-price-prediction/models/house_price_pipeline.pkl")

['C:/Users/haris/house-price-prediction/models/house_price_pipeline.pkl']

**10. Load Saved Pipeline**

In [398]:
loaded_pipeline=joblib.load( "C:/Users/haris/house-price-prediction/models/house_price_pipeline.pkl")
y_pred = loaded_pipeline.predict(X_test)

**11. Build Streamlit application**

In [400]:
#Build in app.py file